import streamlit as st
import pandas as pd

def run_WinningCalculator():
    st.set_page_config(page_title="Win How Much?", page_icon="💰", layout="centered")

    # Title
    st.markdown("""<div class="title-banner"><h1>💰 Win How Much? 💰</h1></div>""", unsafe_allow_html=True)

    # Inputs
    big_bet, small_bet = st.columns(2)
    big_bet = big_bet.number_input("💵 Big Bet", min_value=0, value=0, step=1)
    small_bet = small_bet.number_input("💵 Small Bet", min_value=0, value=0, step=1)

    # Prize structure
    prizes = {
        "First": (2000, 3000), "Second": (1000, 2000), "Third": (490, 800),
        "Starter": (250, None), "Consolation": (60, None)
    }

    # Build table
    rows = []
    for cat, (bp, sp) in prizes.items():
        big_actual, small_actual = (big_bet * bp if bp else 0), (small_bet * sp if sp else 0)
        total = big_actual + small_actual
        rows.append({
            "Category": cat,
            "Total": f"<span style='font-weight:bold; color:green;'>${total:,}</span>" if total else f"${total:,}",
            "Big Prize": f"${bp:,}" if bp else "•", "Big Bet": f"${big_bet:,}", "Big Actual": f"${big_actual:,}",
            "Small Prize": f"${sp:,}" if sp else "•", "Small Bet": f"${small_bet:,}",
            "Small Actual": f"${small_actual:,}"
        })

    df = pd.DataFrame(rows)
    st.markdown(f"<div class='responsive-table'>{df.to_html(escape=False, index=False)}</div>", unsafe_allow_html=True)
    show_4d_bet_types()

def show_4d_bet_types():
    entries = [
        ("1️⃣ Ordinary Entry", "Bet on a specific 4-digit number.", "Ex: **1234**"),
        ("2️⃣ 4-D Roll", "Replace one digit with **'R'** (0–9).", "Ex: **R234** → `0234, 1234, ..., 9234`"),
        ("3️⃣ System Entry", "Bet on all permutations of a number.", "Ex: **1234** → 24 perms"),
        ("4️⃣ iBet", "System Entry from $1 regardless of perms.", "Ex: iBet **1234** covers 24 perms"),
        ("5️⃣ Quickpick", "Random number generated by system.", "Ex: **5821**"),
    ]
    for t, d, e in entries: st.markdown(f"**{t}**\n{d}\n{e}\n")
    st.caption("💡 Tip: Mix bet types depending on your risk and payout style.")
